### ISSUE TITLE
How to gracefully handle a huge file input using pager mode?

### ISSUE THREAD

**Issue by kevinhwang91** [lucc/nvimpager#16]
env: `PAGER=nvimpager`
Some command like journactl opens a huge input file making nvim freeze until it completely loads.
 I make a trick ` alias journalctl='PAGER=less journalctl'` to avoid the problem by using less instead of nvimpager.
Is there a graceful way to handle this problem?

**Comment by lucc** [comment]
What you describe is a know limitation of nvimpager (and nvim/vim and any program using these to display text). [I listed](https://github.com/lucc/nvimpager#known-bugs-and-non-features) it as a known bug since the beginning.

For systemd/journalctl specifically there is the environment variable `SYSTEMD_PAGER` which will override `PAGER`. I think such an approach is to be preferred over aliases as it is more robust.

If you are interested: There is a neovim issue where they also discuss the problem that neovim has to wait for EOF if the buffer is read from stdin: https://github.com/neovim/neovim/issues/9462

**Comment by kevinhwang91** [comment]
Thank you for your answer and solution!
