### ISSUE TITLE
No output when launched with no input

### ISSUE THREAD

**Issue by 3v1n0** [lucc/nvimpager#17]
If I just launch the command with no arguments, the UI is stopping and con Ctrl+C I'm getting:

`^Ccat: /tmp/tmp.v4Vmkmf9h4: No such file or directory`

**Comment by lucc** [comment]
Currently nvimpager reads stdin if no arguments are given. So technically the UI did not stop but is waiting for your input and an EOF (CTRL-D).

The error message comes from a bug that I hope is fixed in the last commit on develop: a79d7e2 

One more point to note is that more and less both exit if no arguments and no text on stdin is given (if stdin is a tty). nvimpager in contrast does not check if stdin is a tty and just waits for text on stdin like cat does.  Maybe nvimpager should behave like more & less in this case. I have to think about that.
