### ISSUE TITLE
Ignores git log highlighting

### ISSUE THREAD

**Issue by p-scvtvlatvs** [lucc/nvimpager#49]
If nvimpager is set as:

git config core.pager nvimpager

no highlighting occurs when git log command is used.

**Comment by lucc** [comment]
I can not reproduce this with the available information.

- Is nvimpager running when you execute `git log` or not? Or is only the highlighting off but nvimpager displays the log in black and white?
- Did you set that option globally or locally in a git repo? Is $PAGER or $GIT_PAGER set?
- Does the highlighting work when you activate it manually with `:setf git`?
- Is the log you tested with longer or shorter than your terminal? Or rather are you running in cat or pager mode?

**Comment by lucc** [comment]
if you are in less and press `h` it should show to help text of less (it says "SUMMARY OF LESS COMMANDS" at the top).  If you are in nvimpager and execute `:lua print(nvimpager)` it should print "table: 0x7f4e48937d20" or so, especially *not* `nil`.

Does the highlighting work when you execute `git log | nvimpager -c` or `git log | nvimpager -p` or `nvimpager ./some/file`?

**Comment by p-scvtvlatvs** [comment]
Yes, it highlights with all the three commands.

**Comment by lucc** [comment]
If these commands work than we can at least conclude that nvimpager works on your machine.

Can you please:
1. find out if nvimpager is run or if another pager is run
2. when nvimpager runs try `setf git` and see if that activates highlighting 
3. tell me what operating system you are on
4. run git diff and the inside nvimpager run `:lua print(require('nvimpager')._testable.detect_parent_process())`

**Comment by p-scvtvlatvs** [comment]
1. Yes, it runs.
2. Yes, highlighting seems to be activated, but everything turns black and white.
3. Arch Linux
4. It returns git.

Apparently, I did something different this time because it started to highlight.  Maybe it's my terminal emulator...

**Comment by lucc** [comment]
That sounds strange. I can currently not reproduce this (in a arch linux container).

Can you try `git log > file ; nvim file`?

**Comment by p-scvtvlatvs** [comment]
Yes, I can see the output in `nvim`.

**Comment by lucc** [comment]
The output or also the highlight?

I am at loss here. It seems that neovim and nvimpager are installed and working. You will have to find a way to debug this and  give more precise info what is happening behind the scenes.

**Comment by p-scvtvlatvs** [comment]
Just the output.

**Comment by lucc** [comment]
Ok, my neovim shows highlighting when I open a file that contains git log output. So the problem seems to be with the runtime files of your neovim.

- what happens if you open the output of `git log` with nvim and then execute `:setf git`? 
- How did you install neovim?
- which version of neovim is installed? 
- are several versions installed? `which -a nvim`
- what is the output of `:filter git scriptnames` in nvimpager with `git log` and what is it for `git diff` (where highlighting seems to work)
- what is the output of `:echo globpath(&rtp, '*/git.vim')`?

**Comment by p-scvtvlatvs** [comment]
1. Nothing.
2. With pacman.
3. 0.4.4
4. Two; `/bin/nvim` and `/usr/bin/nvim`
5. With `git log` is:
    `/usr/share/nvim/runtime/syntax/git.vim`
    `/usr/share/nvim/runtime/ftplugin/git.vim`
   For `git diff` is the same.
6. Nothing for nvim and for nvimpager the same as #5.

**Comment by lucc** [comment]
If you installed your neovim with pacman and still have 0.4.4 I assume you did not do a system update in a *long* time. Mind doing one?

**Comment by lucc** [comment]
I am really out of ideas by now. It seems that your syntax file is loaded correctly but just not applied.  It does not look like you have multible versions of the same file installed. It also looks like the issue is not with nvimpager but already with plain nvim.

You will have to dig around a bit more yourself because it is really difficult for me to do this debugging remotely. If you have any more questions or need help with the debugging please ask but please also provide the info what you have tried and how it went up front.

**Comment by lucc** [comment]
Closed until further info is available.
